<a href="https://colab.research.google.com/github/yash5891/Python-Programming-Assignments/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
arr=np.zeros(3)
arr

array([0., 0., 0.])

In [ ]:
arr=np.ones(10)
arr[5]=0
arr


array([1., 1., 1., 1., 1., 0., 1., 1., 1., 1.])

In [ ]:
arr=np.ones(10)
# arr[0:11]=5
arr*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [ ]:
arr=np.arange(0,9).reshape(3,3)
arr




array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr=np.eye(3,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr=np.random.randn(5,5)
arr

array([[ 0.34020516, -1.17123601, -0.21936332, -1.1851559 ,  1.09208922],
       [ 0.09645925, -0.77449201, -0.61261384,  1.02123353, -0.04915728],
       [ 0.87979891, -0.86106145,  0.44460971, -1.39296327, -0.02243213],
       [ 0.5834065 ,  2.39053372, -1.16773654, -1.36528783,  0.81834139],
       [-0.6979245 , -1.74205845, -0.23601325,  0.85049435,  0.14101028]])

In [ ]:
arr=np.arange(0.01,1.01,0.01)
arr

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [ ]:
arr=np.linspace(0.1,1.01,20)
arr

array([0.1       , 0.14789474, 0.19578947, 0.24368421, 0.29157895,
       0.33947368, 0.38736842, 0.43526316, 0.48315789, 0.53105263,
       0.57894737, 0.62684211, 0.67473684, 0.72263158, 0.77052632,
       0.81842105, 0.86631579, 0.91421053, 0.96210526, 1.01      ])

In [ ]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
mat[0:3,1]


array([ 2,  7, 12])

In [ ]:
mat[4]

array([21, 22, 23, 24, 25])

In [ ]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat.sum()

325

In [ ]:
mat.std()

7.211102550927978

In [ ]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [ ]:

arr=np.array([1,2,3,4])
v=arr[::-1]
v

array([4, 3, 2, 1])

In [ ]:
arr=np.array([10,20,0,0,40,0])
v=arr.nonzero()
v


(array([0, 1, 4]),)

In [ ]:
arr=np.random.randn(10,10)
print(arr.max(),arr.min())

2.9740763414861573 -2.5301937641144385


In [ ]:
arr=np.zeros((10,10))
arr[0:10,0]=1
arr[0,0:10]=1
arr[9,1:10]=1
arr
arr[0:10,9]=1
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
def myadd(x,y):
  return x+y

In [ ]:
myadd=np.frompyfunc(myadd,2,1)
print(myadd([1,2,3,4],[5,6,7,8]))

[6 8 10 12]


In [ ]:
import numpy as np
def checkerboard (shape):
  return np.indices (shape).sum (axis=0) %2
checkerboard ((8, 8))


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
arr=np.arange(0,1,0.10)

arr[1:10]


array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
arr=np.random.randn(10)
arr.sort()
arr

array([-1.6490361 , -1.03444343, -0.57715067, -0.41297361, -0.01921369,
        0.60324205,  0.79214576,  0.87200804,  0.89544658,  2.1343668 ])

In [ ]:
arr=np.random.randn(10)

arr[arr.argmax()]=0
arr




array([ 0.41367178, -0.31673935,  0.96558271, -0.75658885,  0.        ,
       -1.91017343,  0.57318516, -0.47210107,  0.15894479, -0.02846021])

In [6]:
arr=np.array([[56.0, 0.0, 4.4,  68.0],
     [1.2, 104.0, 52.0, 8.0],
     [1.8, 135.0, 99.0, 0.9]])
# burger=arr[0:4,0]
# pizza=arr[0:4,1]
# hamburger=arr[0:4,2]
# cc=arr[0:4,3]
# claculatecarbs_burger=
(arr/arr.sum(axis=0))*100

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])